[package]
name = "drop_tower"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.25.0"
egui_extras = { version = "0.25.0", features = ["all_loaders"] }
serde = "1.0.196"
